services:
  - type: web
    name: ochatbot-backend
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        value: $DATABASE_URL  # Set this in Render dashboard with PostgreSQL URL
      - key: TWILIO_ACCOUNT_SID
        value: $TWILIO_ACCOUNT_SID
      - key: TWILIO_AUTH_TOKEN
        value: $TWILIO_AUTH_TOKEN
      - key: TWILIO_WHATSAPP_NUMBER
        value: $TWILIO_WHATSAPP_NUMBER
      - key: CORS_ORIGINS
        value: $CORS_ORIGINS  # e.g., https://your-vercel-app.vercel.app
